name: Test Proxy-Chain Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y perl make cpanminus luarocks lua5.1 liblua5.1-0-dev libtest-harness-perl

      # Install Lua dependencies via luarocks
      - name: Install Lua dependencies
        run: |
          sudo luarocks install luafilesystem
          sudo luarocks install lua-resty-http

      # Install Perl dependencies and ensure prove
      - name: Install Perl dependencies
        run: |
          sudo cpanm --notest Test::Nginx::Socket::Lua
          # Explicitly install prove if missing
          sudo apt-get install -y perl
          sudo cpanm --notest Test::Harness
          # Verify prove is installed
          /usr/bin/prove --version || echo "Prove installation failed"

      # Clone APISIX and set up test environment with its Nginx
      - name: Setup APISIX environment
        run: |
          git clone https://github.com/apache/apisix.git
          cd apisix
          make deps  # This installs OpenResty (Nginx with Lua support)
          # Ensure servroot directory exists
          mkdir -p t/servroot/conf
          cd ..

      # Copy plugin and test files
      - name: Copy plugin and test files
        run: |
          cp plugins/proxy-chain.lua apisix/apisix/plugins/
          mkdir -p apisix/t/plugin
          cp t/proxy-chain.t apisix/t/plugin/

      # Debug: Check environment and Nginx config
      - name: Debug environment setup
        working-directory: apisix
        run: |
          pwd  # Print current working directory
          ls -la t/servroot/ t/servroot/conf/ || echo "servroot directories missing"
          ./deps/openresty-*/nginx/sbin/nginx -t -p t/servroot/ -c t/servroot/conf/nginx.conf || echo "Nginx config test failed"
          /usr/bin/prove --version || echo "Prove not found in debug step"

      # Run tests with APISIX's Nginx
      - name: Run tests
        working-directory: apisix
        env:
          PATH: "./deps/openresty-*/nginx/sbin:/usr/bin:${PATH}"  # Explicitly add /usr/bin to PATH
        run: |
          prove -I. -v -r t/plugin/proxy-chain.t || true

      # Upload test artifacts if failed
      - name: Upload test artifacts (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: apisix/t/plugin/*.t