name: Test Proxy-Chain Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y perl make cpanminus luarocks lua5.1 liblua5.1-0-dev libtest-harness-perl

      - name: Install Lua dependencies
        run: |
          sudo luarocks install luafilesystem
          sudo luarocks install lua-resty-http

      - name: Install Perl dependencies
        run: |
          sudo cpanm --notest Test::Nginx::Socket::Lua
          sudo cpanm --notest Test::Harness
          /usr/bin/prove --version || echo "Prove installation failed"

      - name: Setup APISIX environment
        run: |
          git clone https://github.com/apache/apisix.git
          cd apisix
          make deps || { echo "make deps failed"; exit 1; }  # Fail if deps installation fails
          mkdir -p t/servroot/conf
          # Debug: List deps directory to find OpenResty
          ls -la deps/
          # Find exact OpenResty path
          OPENRESTY_PATH=$(find deps -maxdepth 2 -type d -name "openresty-*" | head -n 1)
          if [ -z "$OPENRESTY_PATH" ]; then
            echo "Error: OpenResty not found in deps/"
            exit 1
          fi
          echo "OPENRESTY_PATH=${OPENRESTY_PATH}" >> $GITHUB_ENV
          cd ..

      - name: Copy plugin and test files
        run: |
          cp plugins/proxy-chain.lua apisix/apisix/plugins/
          mkdir -p apisix/t/plugin
          cp t/proxy-chain.t apisix/t/plugin/

      - name: Debug environment setup
        working-directory: apisix
        run: |
          pwd
          ls -la t/servroot/ t/servroot/conf/ || echo "servroot directories missing"
          echo "PATH is: $PATH"
          echo "OpenResty path: $OPENRESTY_PATH"
          ${OPENRESTY_PATH}/nginx/sbin/nginx -V 2>&1  # Check Nginx version
          ${OPENRESTY_PATH}/nginx/sbin/nginx -t -p t/servroot/ -c t/servroot/conf/nginx.conf || echo "Nginx config test failed"
          /usr/bin/prove --version

      - name: Run tests
        working-directory: apisix
        env:
          PATH: "${OPENRESTY_PATH}/nginx/sbin:/usr/bin:${PATH}"
          TEST_NGINX_BINARY: "${OPENRESTY_PATH}/nginx/sbin/nginx"  # Explicitly set Nginx binary
        run: |
          nginx -V 2>&1
          prove -I. -v -r t/plugin/proxy-chain.t || true

      - name: Upload test artifacts (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: apisix/t/plugin/*.t